/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/of-planes-and-satellites-db8f1c8cba3b464993e216acbf4a69b9
title: Of Planes and Satellites
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/galaxy/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.04, 0.04, 0.04]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <lineSegments material={materials.sat_gps_material} geometry={nodes.mesh_0.geometry} />
            <lineSegments material={materials.sat_comms_material} geometry={nodes.mesh_1.geometry} />
            <lineSegments material={materials.sat_tech_material} geometry={nodes.mesh_2.geometry} />
            <lineSegments material={materials.sat_earth_material} geometry={nodes.mesh_3.geometry} />
            <lineSegments material={materials.routes_material} geometry={nodes.mesh_4.geometry} />
            <lineSegments material={materials.routes_material} geometry={nodes.mesh_5.geometry} />
            <mesh material={materials.earth} geometry={nodes.mesh_6.geometry} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/galaxy/scene.gltf')
