/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FuncQEE (https://sketchfab.com/FuncQEE)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/puma-concolor-msbmamm214485-276e92326314407d86d2526a8ce3f3a2
title: Puma concolor (MSB:Mamm:214485)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/puma/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-5, 6, 1]} rotation={[1.58, 0, 0]} scale={[0.04, 0.04, 0.04]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_0.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_1.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_2.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_3.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_4.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_5.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_6.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_7.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_8.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_9.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_10.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_11.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_12.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_13.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_14.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_15.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_16.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_17.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_18.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_19.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_20.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_21.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_22.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_23.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_24.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_25.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_26.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_27.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_28.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_29.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_30.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_31.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_32.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_33.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_34.geometry} />
            <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_35.geometry} />
            <group position={[-18.75, 73.22, 19.38]}>
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_36.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_37.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_38.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_39.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_40.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_41.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_42.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_43.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_44.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_45.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_46.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_47.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_48.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_49.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_50.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_51.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_52.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_53.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_54.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_55.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_56.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_57.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_58.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_59.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_60.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_61.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_62.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_63.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_64.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_65.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_66.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_67.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_68.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_69.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_70.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_71.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_72.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_73.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_74.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_75.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_76.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_77.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_78.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_79.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_80.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_81.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_82.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_83.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_84.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_85.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_86.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_87.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_88.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_89.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_90.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_91.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_92.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_93.geometry} />
              <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_94.geometry} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/puma/scene.gltf')
