/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Piotr Pisiak (https://sketchfab.com/piopis)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cyberpunk-speeder-78cf4a37a1604ddeb99651d531d7a0ff
title: Cyberpunk Speeder
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/speeder/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials.material} geometry={nodes.defaultMaterial.geometry} />
          <mesh material={materials.engines} geometry={nodes.defaultMaterial_1.geometry} />
          <mesh material={materials.glass} geometry={nodes.defaultMaterial_2.geometry} />
          <mesh material={materials.low_back} geometry={nodes.defaultMaterial_3.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/speeder/scene.gltf')
